import React from 'react';
import Head from 'next/head'
import Header from '../components/Header';
import Footer from '../components/Footer';

const DefaultLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Header />

        <main>
          {children}
        </main>

        {/* footer */}
        <Footer />
      </div>
    </>
  )
}

export default DefaultLayout